GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRGllZ28iLCJpYXQiOjE2MzYzMjM3MTYsImV4cCI6MTYzNjMyMzczMX0.iXLtGaKppl8OFisk2ZUVFEL7kiPL65TGzobysfn7UAE

###

POST http://localhost:4000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRGllZ28iLCJpYXQiOjE2MzYzMjM5NDF9.V5i0x2XZWMGJD0LY4KmdcniTqxMIPeQljEubxNdOiVc"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
    "username": "Diego"
}

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRGllZ28iLCJpYXQiOjE2MzYzMjM5NDF9.V5i0x2XZWMGJD0LY4KmdcniTqxMIPeQljEubxNdOiVc"
}
